import React from 'react';
import type { TableColumn } from 'react-data-table-component';
import { toast } from 'react-toastify';
import { PageHeader } from '../../../shared/components/PageHeader';
import { SectionCard } from '../../../shared/components/SectionCard';
import { DataTableWrapper } from '../../../shared/components/DataTableWrapper';
import { ErrorBoundary } from '../../../shared/components/ErrorBoundary';
import type { MatchDoeEntry } from '../marketing.types';
import { fetchMatchDoeHistory, getActiveMatchDoe, generateNewMatchDoe } from '../marketing.service';
import { useAuthStore } from '../../../auth/authStore';

export const MatchDoe: React.FC = () => {
  const [active, setActive] = React.useState<MatchDoeEntry | null>(null);
  const [history, setHistory] = React.useState<MatchDoeEntry[]>([]);
  const [loading, setLoading] = React.useState(true);
  const [generating, setGenerating] = React.useState(false);
  const currentUser = useAuthStore((s) => s.user);

  const load = React.useCallback(async () => {
    setLoading(true);
    const [activeCode, hist] = await Promise.all([
      getActiveMatchDoe(),
      fetchMatchDoeHistory(),
    ]);
    setActive(activeCode);
    setHistory(hist);
    setLoading(false);
  }, []);

  React.useEffect(() => { load(); }, [load]);

  const handleRefresh = async () => {
    setGenerating(true);
    try {
      const entry = await generateNewMatchDoe(currentUser?.code ?? 'system');
      setActive(entry);
      toast.success(
        `New Match Code: ${entry.code}. All 3P employees updated; previous code no longer works.`,
      );
      load();
    } catch { toast.error('Failed to generate code'); }
    finally { setGenerating(false); }
  };

  const handleCopyCode = async () => {
    const code = String(active?.code || '').trim();
    if (!code) {
      toast.error('No active code to copy.');
      return;
    }
    try {
      await navigator.clipboard.writeText(code);
      toast.success('Match Code copied.');
    } catch {
      toast.error('Failed to copy code.');
    }
  };

  const columns: TableColumn<MatchDoeEntry>[] = [
    {
      name: 'Code',
      selector: (r) => r.code,
      cell: (r) => (
        <span className={['font-mono text-base font-bold', r.isActive ? 'text-primary' : 'text-slate-400'].join(' ')}>
          {r.code}
        </span>
      ),
      width: '110px',
    },
    { name: 'Generated At', selector: (r) => r.generatedAt, format: (r) => new Date(r.generatedAt).toLocaleString() },
    { name: 'Generated By', selector: (r) => r.generatedBy },
    {
      name: 'Active',
      cell: (r) => (
        <span className={[
          'rounded-full px-2.5 py-0.5 text-xs font-bold',
          r.isActive ? 'bg-emerald-100 text-emerald-700' : 'bg-slate-100 text-slate-500',
        ].join(' ')}>
          {r.isActive ? 'Active' : 'Expired'}
        </span>
      ),
      width: '100px',
    },
  ];

  return (
    <ErrorBoundary>
      <PageHeader
        title="Match Code"
        subtitle="One active code for all 3P employees. Generating a new code updates every 3P record and invalidates the old code for uploads."
      />

      <SectionCard title="Active Match Code" className="mb-5">
        {loading ? (
          <div className="flex h-24 items-center justify-center">
            <div className="h-6 w-6 animate-spin rounded-full border-4 border-primary border-t-transparent" />
          </div>
        ) : (
          <div className="flex flex-wrap items-center gap-8">
            <div className="flex flex-col gap-1">
              <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Current Active Code</p>
              <p className="font-mono text-6xl font-black tracking-widest text-primary">
                {active?.code ?? '—'}
              </p>
              {active && (
                <p className="text-xs text-slate-400">
                  Generated {new Date(active.generatedAt).toLocaleString()} by {active.generatedBy}
                </p>
              )}
            </div>
            <div className="flex flex-col gap-2">
              <button
                type="button"
                disabled={generating}
                onClick={handleRefresh}
                className="flex items-center gap-2 rounded-xl bg-primary px-6 py-3 text-sm font-bold text-white shadow hover:bg-primary-dark disabled:opacity-60"
              >
                <svg className={['h-4 w-4', generating ? 'animate-spin' : ''].join(' ')} fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
                </svg>
                {generating ? 'Generating…' : 'Refresh Code'}
              </button>
              {/* <button
                type="button"
                onClick={handleCopyCode}
                className="rounded-xl border border-slate-300 px-6 py-2 text-sm font-bold text-slate-700 hover:bg-slate-50"
              >
                Copy Code
              </button> */}
            </div>
          </div>
        )}
      </SectionCard>

      <SectionCard title="Code History">
        <DataTableWrapper columns={columns} data={history} loading={loading} searchable={false} />
      </SectionCard>
    </ErrorBoundary>
  );
};
