import React from 'react';
import type { TableColumn } from 'react-data-table-component';
import { toast } from 'react-toastify';
import { formatDateTimeDDMMYYYY } from '../../../shared/utils/dateFormat';
import { PageHeader } from '../../../shared/components/PageHeader';
import { SectionCard } from '../../../shared/components/SectionCard';
import { DataTableWrapper } from '../../../shared/components/DataTableWrapper';
import { ErrorBoundary } from '../../../shared/components/ErrorBoundary';
import type { MatchDoeEntry } from '../marketing.types';
import {
  fetchMatchDoeHistory,
  generateNewMatchDoe,
  updateMatchDoeStatus,
} from '../marketing.service';
import { useAuthStore } from '../../../auth/authStore';
import { api } from '../../../shared/services/apiService';

type ThreePcOption = { code: string; name: string };

const selectClass =
  'h-10 min-w-[12rem] rounded-lg border border-slate-300 bg-white px-3 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/20';

function validityLabel(entry: MatchDoeEntry): string {
  if (!entry.validUntil) return '—';
  const until = new Date(entry.validUntil).getTime();
  if (until < Date.now()) return 'Expired';
  const mins = Math.max(0, Math.ceil((until - Date.now()) / 60000));
  return `Valid ${mins} min`;
}

export const MatchDoe: React.FC = () => {
  const [history, setHistory] = React.useState<MatchDoeEntry[]>([]);
  const [threePcOptions, setThreePcOptions] = React.useState<ThreePcOption[]>([]);
  const [selected3p, setSelected3p] = React.useState('');
  const [loading, setLoading] = React.useState(true);
  const [generating, setGenerating] = React.useState(false);
  const [statusSavingId, setStatusSavingId] = React.useState<string | null>(null);
  const currentUser = useAuthStore((s) => s.user);

  const load = React.useCallback(async () => {
    setLoading(true);
    try {
      const [hist, codesRes] = await Promise.all([
        fetchMatchDoeHistory(),
        api.get<{ employees?: Array<{ code: string; name?: string }> }>('/api/employees/codes?type=3pc'),
      ]);
      setHistory(hist);
      const opts = (codesRes.employees || [])
        .map((c) => ({ code: String(c.code || '').toUpperCase(), name: String(c.name || '').trim() }))
        .filter((c) => c.code);
      setThreePcOptions(opts);
    } catch {
      toast.error('Failed to load match code data');
    } finally {
      setLoading(false);
    }
  }, []);

  React.useEffect(() => { void load(); }, [load]);

  const handleGenerate = async () => {
    if (!selected3p) {
      toast.error('Select a 3P employee first.');
      return;
    }
    setGenerating(true);
    try {
      const entry = await generateNewMatchDoe(currentUser?.code ?? 'system', selected3p);
      toast.success(`Match Code ${entry.code} generated for ${selected3p}. Valid for 45 minutes.`);
      await load();
    } catch (e) {
      toast.error(e instanceof Error ? e.message : 'Failed to generate code');
    } finally {
      setGenerating(false);
    }
  };

  const handleStatusChange = async (row: MatchDoeEntry, isActive: boolean) => {
    setStatusSavingId(row.id);
    try {
      await updateMatchDoeStatus(row.id, isActive);
      toast.success(`Code ${row.code} set to ${isActive ? 'Active' : 'Inactive'}.`);
      await load();
    } catch (e) {
      toast.error(e instanceof Error ? e.message : 'Failed to update status');
    } finally {
      setStatusSavingId(null);
    }
  };

  const activeForSelected = history.find(
    (r) => r.generatorFor === selected3p && r.isActive && validityLabel(r) !== 'Expired',
  );

  const columns: TableColumn<MatchDoeEntry>[] = [
    {
      name: 'Code',
      selector: (r) => r.code,
      cell: (r) => (
        <span className={['font-mono text-base font-bold', r.isActive ? 'text-primary' : 'text-slate-400'].join(' ')}>
          {r.code}
        </span>
      ),
      width: '100px',
    },
    {
      name: 'Generator For',
      selector: (r) => r.generatorFor || '',
      cell: (r) => <span className="font-semibold uppercase">{r.generatorFor || '—'}</span>,
      minWidth: '8rem',
    },
    {
      name: 'Validity',
      cell: (r) => (
        <span className="text-xs font-semibold text-slate-700">
          {r.validUntil ? formatDateTimeDDMMYYYY(r.validUntil) : '—'}
          <span className="mt-0.5 block text-slate-500">{validityLabel(r)}</span>
        </span>
      ),
      minWidth: '9rem',
    },
    { name: 'Generated At', selector: (r) => r.generatedAt, format: (r) => formatDateTimeDDMMYYYY(r.generatedAt) || '—' },
    { name: 'Generated By', selector: (r) => r.generatedBy },
    {
      name: 'Status',
      cell: (r) => (
        <select
          className="h-8 min-w-[6.5rem] rounded-lg border border-slate-300 bg-white px-2 text-xs font-semibold outline-none focus:border-primary disabled:opacity-60"
          value={r.isActive ? 'Active' : 'Inactive'}
          disabled={statusSavingId === r.id}
          onChange={(e) => void handleStatusChange(r, e.target.value === 'Active')}
        >
          <option value="Active">Active</option>
          <option value="Inactive">Inactive</option>
        </select>
      ),
      width: '7.5rem',
    },
  ];

  return (
    <ErrorBoundary>
      <PageHeader
        title="Match Code"
        subtitle="Select a 3P employee, then generate a unique match code valid for 45 minutes."
      />

      <SectionCard title="Generate Match Code" className="mb-5">
        <div className="flex flex-wrap items-end gap-4">
          <div>
            <label className="mb-1 block text-xs font-semibold uppercase tracking-wide text-slate-600">3P Employee</label>
            <select className={selectClass} value={selected3p} onChange={(e) => setSelected3p(e.target.value)}>
              <option value="">Select 3P employee</option>
              {threePcOptions.map((o) => (
                <option key={o.code} value={o.code}>
                  {o.code}{o.name ? ` — ${o.name}` : ''}
                </option>
              ))}
            </select>
          </div>
          <button
            type="button"
            disabled={generating || !selected3p}
            onClick={() => void handleGenerate()}
            className="flex h-10 items-center gap-2 rounded-xl bg-primary px-6 text-sm font-bold text-white shadow hover:bg-primary-dark disabled:opacity-60"
          >
            {generating ? 'Generating…' : 'Generate Match Code'}
          </button>
        </div>
        {activeForSelected ? (
          <p className="mt-3 text-sm text-slate-600">
            Active code for <strong>{selected3p}</strong>:{' '}
            <span className="font-mono text-lg font-bold text-primary">{activeForSelected.code}</span>
            {' · '}
            {validityLabel(activeForSelected)}
          </p>
        ) : null}
      </SectionCard>

      <SectionCard title="Code History">
        <DataTableWrapper columns={columns} data={history} loading={loading} searchable={false} />
      </SectionCard>
    </ErrorBoundary>
  );
};
